#!/bin/bash

#check if the argument is not provided
if [ -z "$1" ]; then
  echo "vpc id not provided"
else
 export VPC_ID=$1
fi 


if [ -z "$2" ]; then
  echo "Internet gateway id not provided"
else
 export IGW_ID=$2
fi

if [ -z "$3" ]; then
  echo "route table id not provided"
else
 export RT_ID=$3
fi

if [ -z "$4" ]; then
  echo "subnet id not provided"
else
 export SUBNET_ID=$4
fi

#main route table will be automactically deleted while deleting vpc

#delete the subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID --output text

#detach the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --output text

#delete the IGW
 aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID --output text

#delete vpc
aws ec2 delete-vpc \
--vpc-id $VPC_ID \
--output text