#!/bin/bash

#checksum for bucket name
if [ -z "$1" ]; then
   echo "there is a need for bucket name eg ./bucket my-bucket-name"
   exit 1
fi

BUCKET_NAME="$1"

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ap-south-1" \
--query Location \
--output text