#!/bin/bash

echo "==delete objects"

set -e

if [ -z "$1" ]; then
  echo "there needs to be bucket name"
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
--output json \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > ./tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --output json --delete file://tmp/delete_objects.json 