#!/bin/bash

echo "==put object"

if [ -z "$1" ]; then
  echo "there needs to be a bucket name"
  exit 1
fi

if [ -z "$2" ]; then
    echo "there needs to be a filename "
    exit 1
 fi 

 BUCKET_NAME=$1
 FILENAME=$2

 OBJECT_KEY=$(basename "$FILENAME")

 aws s3api put-object \
 --bucket $BUCKET_NAME \
 --body $FILENAME \
 --key $OBJECT_KEY \
 --output text
