#!/bin/bash
echo "== sync"
set -e

#check for the bucket name
if [ -z "$1" ]; then
   echo "there is a need for bucket name eg ./bucket my-bucket-name"
   exit 1
fi


#check for filename prefix 
if [ -z "$2" ]; then
  echo "there needs to be a filename"
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR="/tmp/s3-bash-scripts"

rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files